#commit requirement 
name: Commit

on:
  commit:
    branches:
      - main

jobs:
  commit:

    runs-on: ubuntu-latest

    steps:
      - name: Display commit
        run: echo "commited"

#pull requirement 
name: Pull

on:
  pull:
    branches:
      - main

jobs:
  pull:

    runs-on: ubuntu-latest

    steps:
      - name: Display Pull
        run: echo "Pulled"

#RUns when manually ran 
name: Manually Ran 

on:
  run:
    branches:
      - main

jobs:
  hello:

    runs-on: ubuntu-latest

    steps:
      - name: Display manually ran
        run: echo "manually ran"

#Installs packages

#Runs all tests
name: Run tests

on:
  test:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Display hello world
        run: echo "tests ran"

